kind: Pod           # Object type (Pod)
apiVersion: v1        
metadata:
  name: testpod1      

spec:
  containers:
    - name: c01                    # First container
      image: nginx                 # Using the official Nginx image
      ports:
        - containerPort: 80         # Exposing port 80 for the web server
