kind: Pod                              # Object type (must be "Pod", not "pod")
apiVersion: v1                         # API version
metadata:                               # Corrected typo (was "matadata")
  name: testpod                         # Name of the Pod

spec:
  containers:                           # Containers details
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo 'hello-sai'; sleep 5; done"]
